#!/data/data/com.termux/files/usr/bin/bash

# Auto gelud

# coded By Mr.Kovlak.Jr

# Recode Awto Gelud Kita

#Pm Gua Bangsatt

# Bersihkan Layar

clear

cd module

python2 please.py


blue='\e[0;34'

cyan='\e[0;36m'

green='\e[0;34m'

okegreen='\033[92m'

lightgreen='\e[1;32m'

white='\e[1;37m'

red='\e[1;31m'

yellow='\e[1;33m'


###################################################

# CTRL C

###################################################

trap ctXrl_c INT

ctrl_c() {

clear

echo -e $gold"[#]> (Ctrl + C ) Detected, Trying To Exit ... "

sleep 1

echo ""

echo -e $blue"[#]> semoga bermanfaat "

sleep 1

echo ""

read enter

exit

}


echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>" 

echo -e $gold"=Author :Mr.KOVLAK.Jr =" 

echo -e $gold"=Kontak :085848812535 ="

echo -e $blue"=Date :12-06-2018 ="

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo ""

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $yellow"• 01) MBF"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $red"• 02 ) Auto Follower Instragam"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $okegreen"• 03 ) Spam Nomer Telepon"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $yellow"• 04 ) Install Metasploit"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $blue"• 05 ) Install Webdav"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $lightgreen"• 06 ) Santet Online Buat Nyantet Orang;)"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $yellow"• 07 ) Install WPScan"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $red"• 08 ) Install D-Tect"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $okegreen"• 09 ) Install Hunner"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $cyan"• 10 ) Install Red Hawk"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $blue"• 11 ) Install Ngrok"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $lightgreen"• 12 ) Intall Goggle-Dork"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $yellow"• 13 ) Install viSQL"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $red"• 14 ) Install Ubuntu"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $okegreen"• 15 ) Install Kali NetHunter"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e$yellow"• 16 ) Luwak White Coffe Paswordnya"

echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $red"• 00 ) Exit"
echo $gold"<><><><><><><><><><><><><><><><><><><><><><><><><>"

echo -e $white""

read -p "[Mr.KOVLAK.Jr<^> " bro;


if [ $bro = 01 ] || [ $bro = 01 ]

then

clear

toilet "Mr.KOVLAK.Jr"

pkg install python2

pkg install git

git clone https://github.com/pirmansx/mbf

cd mbf/

pip2 install mechanize

python2 MBF.py

fi


if [ $bro = 02 ] || [ $bro = 02 ]

then

clear

toilet "Mr.KOVLAK.Jr"

pkg install git

git clone https://github.com/MissProxy/followig

cd followig

ls

chmod +x setup.py

python setup.py install

fi


if [ $bro = 03 ] || [ $bro = 03 ]

then

clear

toilet "Mr.KOVLAK.Jr"

pkg install php 

pkg install curl

curl https://pastebin.com/raw/9BYy1JVc -o jdid.php

ls

php jdid.php

fi

if [ $bro = 04 ] || [ $bro = 04 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

apt install git

apt install wget

wget https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh

chmod 777 install.sh

sh install.sh

echo -e $red" Done Install "

fi


if [ $bro = 05 ] || [ $bro = 05 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

apt install python2

pip2 install urllib3 chardet certifi idna requests

apt install openssl curl

pkg install libcurl

mkdir webdav

cd ~/webdav

wget https://pastebin.com/raw/HnVyQPtR -O webdav.py

chmod 777 webdav.py

cd ~/

echo -e $red" kamu dapet perawan "

fi


if [ $bro = 06 ] || [ $bro = 06 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update&&apt upgrade

apt install git

git clone https://github.com/Gameye98/santet-online

echo -e $red" sekarang anda dukun "

fi


if [ $bro = 07 ] || [ $bro = 07 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt-get update && apt-get upgrade

apt install ruby

apt install curl

apt install git

git clone https://github.com/wpscanteam/wpscan

cd ~/wpscan

gem install bundle

bundle config build.nokogiri --use-system-libraries

bundle install

ruby wpscan.rb --update

cd ~/

echo -e $red" eaa berhasil "

fi


if [ $bro = 08 ] || [ $bro = 08 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt-get update && apt-get upgrade

apt-get install git

apt-get install python2

git clone https://github.com/shawarkhanethicalhacker/D-TECT

echo -e $red" crot didalem "

fi



if [ $bro = 09 ] || [ $bro = 09 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt-get update && apt-get upgrade

apt install python

apt install git

git clone https://github.com/b3-v3r/Hunner

echo -e $red" anda beruntung "

fi


if [ $bro = 10 ] || [ $bro = 10 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

apt install php

apt install git

git clone https://github.com/Tuhinshubhra/RED_HAWK

echo -e $green" selesai tod "

fi


if [ $bro = 11 ] || [ $bro = 11 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt install wget

mkdir ngrok

cd ~/ngrok

wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip

unzip ngrok-stable-linux-arm.zip

cd ~/

echo -e $red" dah eaaa "

fi


if [ $bro = 12 ] || [ $bro = 12 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update&&apt upgrade

apt install python2

apt install git

git clone https://github.com/XG77Z10/Google-Dork

pip2 install termcolor

echo -e $orange" kurangi bokep "

fi


if [ $bro = 13 ] || [ $bro = 13 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

pkg install git

pkg install python2

git clone https://github.com/blackvkng/viSQL.git

cd ~/viSQL

chmod 777 viSQL.py

cd ~/viSQL

echo -e $red" selesai tod "

fi


if [ $bro = 14 ] || [ $bro = 14 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

apt install git

apt install wget

apt install proot

git clone https://github.com/Neo-Oli/termux-ubuntu.git

cd ~/termux-ubuntu

chmod +x ubuntu.sh

sh ubuntu.sh

echo " Fix network please wait "

sleep 1

echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/resolv.conf

echo -e $red" selesai tod "

fi


if [ $bro = 15 ] || [ $bro = 15 ]

then

clear

toilet "Mr.KOVLAK.Jr"

apt update && apt upgrade

apt install git

git clone https://github.com/Hax4us/Nethunter-In-Termux.git

cd ~/Nethunter-In-Termux

chmod 777 kalinethunter

sh kalinethunter

echo -e $red" kamu milea ya "

fi

if [ $bro = 16 ] || [ $bro = 16 ]

echo "Yamaha Semakin Didepan"

fi

if [ $act = 00 ] || [ $act = 00 ]

then

echo -e $green" THANKS UDAH MENCOBA "

sleep 1

echo -e $yellow" INDONESIAN SECURITY HUNTER "

sleep 1

echo -e $gold" Untuk Terakhir Disini Ada Sulap "

sleep 1

echo -e $gold" 3 "

sleep 1

echo -e $gold" 2 "

sleep 1

echo -e $gold" 1 "

sleep 1

clear

echo -e $gold" Terhapus Bagaikan Sulap "

exit

fi

